name: Build and Release Percona PostgreSQL Snap

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  SNAP_NAME: percona-postgresql

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Snapcraft
      uses: snapcore/action-build@v1
      id: snapcraft

    - name: Upload snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SNAP_NAME }}-snap
        path: ${{ steps.snapcraft.outputs.snap }}

  